version: "3.9"

services:
  explorer:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - db
    networks:
      - service

  db:
    container_name: dev-db
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - service

#  redis:
#    container_name: redis
#    image: "redis:latest"
#    ports:
#      - 6379:6379
#    networks:
#      - service

networks:
  service:
    driver: bridge